-- ============================================================================
--  UNIFY FEEDBACKS  —  create the single unified feedback table + migrate data
-- ----------------------------------------------------------------------------
--  Merges the two legacy feedback extension tables
--      childsmile_app_tutor_feedback      (tutor feedback)
--      childsmile_app_general_v_feedback  (volunteer feedback)
--  together with their shared parent
--      childsmile_app_feedback
--  into ONE new table:
--      childsmile_app_feedbacks           (models.Feedbacks, managed = False)
--
--  The three legacy tables are LEFT IN PLACE as a backup. They are dropped in a
--  SEPARATE, later PR via drop_old_feedback_tables.sql once prod is verified.
--
--  Target: PostgreSQL.  Safe to re-run (table guarded with IF NOT EXISTS, data
--  copy TRUNCATEs first).  No data loss: every existing feedback row is copied.
--
--  Field mapping:
--    staff_id      <- feedback.staff_id            (the actual submitter; may be an
--                                                   admin/coordinator "filling for")
--    filler_id     <- tutors.staff_id / general_volunteer.staff_id
--                                                  (the tutor/volunteer the feedback
--                                                   is ATTRIBUTED to; NULL if that
--                                                   tutor/volunteer row is gone)
--    filler_name   <- tutor_feedback.tutor_name / general_v_feedback.volunteer_name
--    subject_name  <- tutor_feedback.tutee_name  / general_v_feedback.child_name
--    is_it_your_tutee <- tutor_feedback.is_it_your_tutee (NULL for volunteer rows)
-- ============================================================================

BEGIN;

-- 1) Create the unified table (mirrors models.Feedbacks) -----------------------
CREATE TABLE IF NOT EXISTS public.childsmile_app_feedbacks (
    feedback_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp"            timestamp with time zone NOT NULL,
    event_date             timestamp with time zone NOT NULL,
    staff_id               integer NOT NULL,
    filler_id              integer,
    filler_name            character varying(255) NOT NULL,
    subject_name           character varying(255),
    is_it_your_tutee       boolean,
    description            text NOT NULL,
    exceptional_events     text,
    anything_else          text,
    comments               text,
    feedback_type          character varying(50) NOT NULL,
    hospital_name          character varying(50),
    additional_volunteers  text,
    names                  character varying(500),
    phones                 character varying(500),
    other_information      text,
    CONSTRAINT childsmile_app_feedbacks_staff_id_fk
        FOREIGN KEY (staff_id) REFERENCES public.childsmile_app_staff (staff_id)
        ON DELETE CASCADE,
    CONSTRAINT childsmile_app_feedbacks_filler_id_fk
        FOREIGN KEY (filler_id) REFERENCES public.childsmile_app_staff (staff_id)
        ON DELETE SET NULL
);

ALTER TABLE public.childsmile_app_feedbacks OWNER TO child_smile_user;

CREATE INDEX IF NOT EXISTS childsmile_app_feedbacks_staff_id_idx
    ON public.childsmile_app_feedbacks (staff_id);
CREATE INDEX IF NOT EXISTS childsmile_app_feedbacks_filler_id_idx
    ON public.childsmile_app_feedbacks (filler_id);

-- 2) Copy existing data -------------------------------------------------------
--    Re-uses the original feedback_id values (each legacy feedback row has EXACTLY
--    one child row — tutor XOR volunteer — so ids never collide).
TRUNCATE TABLE public.childsmile_app_feedbacks;

-- 2a) Tutor feedbacks
INSERT INTO public.childsmile_app_feedbacks (
    feedback_id, "timestamp", event_date, staff_id, filler_id, filler_name,
    subject_name, is_it_your_tutee, description, exceptional_events, anything_else,
    comments, feedback_type, hospital_name, additional_volunteers, names, phones, other_information
)
SELECT
    f.feedback_id,
    f."timestamp",
    f.event_date,
    f.staff_id,
    t.staff_id,
    tf.tutor_name,
    tf.tutee_name,
    tf.is_it_your_tutee,
    f.description,
    f.exceptional_events,
    f.anything_else,
    f.comments,
    f.feedback_type,
    f.hospital_name,
    f.additional_volunteers,
    f.names,
    f.phones,
    f.other_information
FROM public.childsmile_app_feedback f
JOIN public.childsmile_app_tutor_feedback tf ON tf.feedback_id_id = f.feedback_id
LEFT JOIN public.childsmile_app_tutors t ON t.id_id = tf.tutor_id;

-- 2b) Volunteer feedbacks
INSERT INTO public.childsmile_app_feedbacks (
    feedback_id, "timestamp", event_date, staff_id, filler_id, filler_name,
    subject_name, is_it_your_tutee, description, exceptional_events, anything_else,
    comments, feedback_type, hospital_name, additional_volunteers, names, phones, other_information
)
SELECT
    f.feedback_id,
    f."timestamp",
    f.event_date,
    f.staff_id,
    gv.staff_id,
    gvf.volunteer_name,
    gvf.child_name,
    NULL,
    f.description,
    f.exceptional_events,
    f.anything_else,
    f.comments,
    f.feedback_type,
    f.hospital_name,
    f.additional_volunteers,
    f.names,
    f.phones,
    f.other_information
FROM public.childsmile_app_feedback f
JOIN public.childsmile_app_general_v_feedback gvf ON gvf.feedback_id_id = f.feedback_id
LEFT JOIN public.childsmile_app_general_volunteer gv ON gv.id_id = gvf.volunteer_id;

-- 3) Advance the identity sequence past the copied ids ------------------------
SELECT setval(
    pg_get_serial_sequence('public.childsmile_app_feedbacks', 'feedback_id'),
    COALESCE((SELECT MAX(feedback_id) FROM public.childsmile_app_feedbacks), 1),
    true
);

COMMIT;

-- 4) Verification (run manually; all three counts should reconcile) -----------
--   Rows copied should equal tutor rows + volunteer rows:
--     SELECT
--       (SELECT COUNT(*) FROM public.childsmile_app_feedbacks)            AS unified,
--       (SELECT COUNT(*) FROM public.childsmile_app_tutor_feedback)       AS tutor,
--       (SELECT COUNT(*) FROM public.childsmile_app_general_v_feedback)   AS volunteer;
--   Any legacy feedback with NO child row (orphan, never happens in normal flow)
--   is intentionally not copied — list them with:
--     SELECT f.feedback_id FROM public.childsmile_app_feedback f
--     LEFT JOIN public.childsmile_app_tutor_feedback tf     ON tf.feedback_id_id = f.feedback_id
--     LEFT JOIN public.childsmile_app_general_v_feedback gv ON gv.feedback_id_id = f.feedback_id
--     WHERE tf.feedback_id_id IS NULL AND gv.feedback_id_id IS NULL;
