"""
Django settings for childsmile project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # Add this import
import os
import json
import boto3
from django.core.exceptions import ImproperlyConfigured
import socket

# Load environment variables from .env file
load_dotenv()  # Add this line
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret")

IS_PROD = os.environ.get("DJANGO_ENV") == "production"
ALB_URL = "http://child-smile-app-alb-1403896092.il-central-1.elb.amazonaws.com"
LOCAL_URL = "http://localhost:9000"
# Temporary CloudFront URL for frontend testing
CLOUDFRONT_URL = "https://app.achildssmile.org.il"  # replace with your actual CF URL

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.31.51.180','localhost','127.0.0.1','app.achildssmile.org.il','child-smile-app-alb-1403896092.il-central-1.elb.amazonaws.com']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'childsmile_app',
    'corsheaders',
    'django.contrib.sites',  # Required for allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]
SITE_ID = 1


# Add this at the bottom of your settings.py
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

MIDDLEWARE = [
   "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
]

# Allauth settings to minimize interference
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable email verification
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_SESSION_REMEMBER = None

# This tells allauth to only handle /accounts/ URLs
ACCOUNT_LOGIN_URL = '/accounts/login/'
ACCOUNT_LOGOUT_URL = '/accounts/logout/'

ROOT_URLCONF = "childsmile.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "childsmile.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Detect whether running on EC2 or local
import json
import os
import boto3
import requests
from functools import wraps
from psycopg2 import OperationalError

def is_ec2():
    """Detect EC2 instance by querying the metadata service."""
    try:
        # Get a session token (IMDSv2)
        token = requests.put(
            "http://169.254.169.254/latest/api/token",
            headers={"X-aws-ec2-metadata-token-ttl-seconds": "60"},
            timeout=0.2
        ).text

        # Try to get instance-id using that token
        response = requests.get(
            "http://169.254.169.254/latest/meta-data/instance-id",
            headers={"X-aws-ec2-metadata-token": token},
            timeout=0.2
        )

        return response.status_code == 200
    except requests.RequestException:
        return False

on_ec2 = is_ec2()

def get_rds_credentials():
    """Get DB credentials from Secrets Manager if on EC2, else from .env"""
    if on_ec2:
        secret_name = os.environ.get("AWS_SECRET_NAME")
        region_name = os.environ.get("AWS_REGION", "il-central-1")
        client = boto3.client("secretsmanager", region_name=region_name)
        secret_value = client.get_secret_value(SecretId=secret_name)
        secret_dict = json.loads(secret_value["SecretString"])
        return secret_dict
    else:
        return {
            "username": os.getenv("DB_USER", "child_smile_user"),
            "password": os.getenv("DB_PASSWORD", "fallback_password"),
        }
# Lazy fetch callable for Django
def get_rds_password():
    return get_rds_credentials()["password"]

# Optional: retry wrapper for auth failures
def retry_on_auth_failure(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except OperationalError as e:
            if "password authentication failed" in str(e):
                kwargs['password'] = get_rds_password()
                return fn(*args, **kwargs)
            raise
    return wrapper

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'child_smile_db',
        'USER': 'child_smile_user',
        'PASSWORD': os.getenv('DB_PASSWORD'),# if not on_ec2 else get_rds_password,
        'HOST': (
            'child-smile-db.cpooguksy04d.il-central-1.rds.amazonaws.com'
            if on_ec2
            else 'localhost'
        ),
        'PORT': '5432',
        'CONN_MAX_AGE': 0,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# the frontend  directory is the C:\Dev\FinalProjectOpenU\childsmile\frontend, we have public folder in it with assets dir , and js and css in src folder
STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'frontend/src'),  # Adjust the path to your static files
# ]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [CLOUDFRONT_URL] if IS_PROD else [LOCAL_URL]
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True #False if not IS_PROD else True

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # legacy login
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https" if IS_PROD else "http"
CSRF_TRUSTED_ORIGINS = [LOCAL_URL] if not IS_PROD else [CLOUDFRONT_URL]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


LOGIN_REDIRECT_URL = '/tasks'  # Redirect to your app's home page
# Replace the existing SOCIALACCOUNT_AUTO_SIGNUP line with:
SOCIALACCOUNT_ADAPTER = 'childsmile_app.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = False  # Don't auto-create accounts

# Add these Google OAuth settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Add these settings to skip the ugly confirmation page
SOCIALACCOUNT_LOGIN_ON_GET = True  # Skip confirmation page
ACCOUNT_EMAIL_VERIFICATION = 'none'  # You already have this
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-create user accounts
ACCOUNT_LOGOUT_ON_GET = True  # Optional: allow GET logout

# Fix the deprecated setting
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
# Redirect to React frontend after Google login
LOGIN_REDIRECT_URL = CLOUDFRONT_URL + "/#/google-success" if IS_PROD else LOCAL_URL + "/google-success"




# Replace your gmail settings with an App Password
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'noreply@send.amitssmile.com'

# TOTP Settings
TOTP_EXPIRY_MINUTES = 5
TOTP_MAX_ATTEMPTS = 3
