# Generated by Django 5.1.4 on 2025-01-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childsmile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('Candidate Interview for Tutoring', 'Candidate Interview'), ('Adding a Tutor', 'Add Tutor'), ('Matching a Tutee', 'Match Tutee'), ('Adding a Family', 'Add Family'), ('Family Status Check', 'Family Status Check'), ('Family Update', 'Family Update'), ('Family Deletion', 'Family Deletion'), ('Adding a Healthy Member', 'Add Healthy Member'), ('Reviewing a Mature Individual', 'Review Mature'), ('Tutoring', 'Tutoring'), ('Tutoring Feedback', 'Tutoring Feedback'), ('Reviewing Tutor Feedback', 'Review Tutor Feedback'), ('General Volunteer Feedback', 'General Volunteer Feedback'), ('Reviewing General Volunteer Feedback', 'Review General Volunteer Feedback'), ('Feedback Report Generation', 'Feedback Report Generation')], max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='childsmile_app.staff')),
                ('related_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childsmile_app.familymember')),
                ('related_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childsmile_app.family')),
                ('related_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childsmile_app.tutor')),
            ],
        ),
    ]
