# 0005_override_roles_and_permissions.py
from django.db import migrations

def override_roles_and_permissions(apps, schema_editor):
    Role = apps.get_model('childsmile_app', 'Role')
    Permissions = apps.get_model('childsmile_app', 'Permissions')

    # Delete existing roles and permissions
    Permissions.objects.all().delete()
    Role.objects.all().delete()

    # Create new roles from dev order.sql
    roles = [
        'Technical Coordinator',
        'Volunteer Coordinator',
        'Families Coordinator',
        'Tutors Coordinator',
        'Matures Coordinator',
        'Healthy Kids Coordinator',
        'System Administrator',
        'General Volunteer',
        'Tutor'
    ]

    role_objects = {}
    for role_name in roles:
        role = Role.objects.create(role_name=role_name)
        role_objects[role_name] = role

    # Insert permissions from dev order.sql
    permissions = [
        # System Administrator
        ('System Administrator', 'childsmile_app_role', 'CREATE'),
        ('System Administrator', 'childsmile_app_role', 'UPDATE'),
        ('System Administrator', 'childsmile_app_role', 'DELETE'),
        ('System Administrator', 'childsmile_app_role', 'VIEW'),
        ('System Administrator', 'childsmile_app_permissions', 'CREATE'),
        ('System Administrator', 'childsmile_app_permissions', 'UPDATE'),
        ('System Administrator', 'childsmile_app_permissions', 'DELETE'),
        ('System Administrator', 'childsmile_app_permissions', 'VIEW'),
        ('System Administrator', 'childsmile_app_staff', 'CREATE'),
        ('System Administrator', 'childsmile_app_staff', 'UPDATE'),
        ('System Administrator', 'childsmile_app_staff', 'DELETE'),
        ('System Administrator', 'childsmile_app_staff', 'VIEW'),
        ('System Administrator', 'childsmile_app_signedup', 'CREATE'),
        ('System Administrator', 'childsmile_app_signedup', 'UPDATE'),
        ('System Administrator', 'childsmile_app_signedup', 'DELETE'),
        ('System Administrator', 'childsmile_app_signedup', 'VIEW'),
        ('System Administrator', 'childsmile_app_general_volunteer', 'CREATE'),
        ('System Administrator', 'childsmile_app_general_volunteer', 'UPDATE'),
        ('System Administrator', 'childsmile_app_general_volunteer', 'DELETE'),
        ('System Administrator', 'childsmile_app_general_volunteer', 'VIEW'),
        ('System Administrator', 'childsmile_app_pending_tutor', 'CREATE'),
        ('System Administrator', 'childsmile_app_pending_tutor', 'UPDATE'),
        ('System Administrator', 'childsmile_app_pending_tutor', 'DELETE'),
        ('System Administrator', 'childsmile_app_pending_tutor', 'VIEW'),
        ('System Administrator', 'childsmile_app_tutors', 'CREATE'),
        ('System Administrator', 'childsmile_app_tutors', 'UPDATE'),
        ('System Administrator', 'childsmile_app_tutors', 'DELETE'),
        ('System Administrator', 'childsmile_app_tutors', 'VIEW'),
        ('System Administrator', 'childsmile_app_children', 'CREATE'),
        ('System Administrator', 'childsmile_app_children', 'UPDATE'),
        ('System Administrator', 'childsmile_app_children', 'DELETE'),
        ('System Administrator', 'childsmile_app_children', 'VIEW'),
        ('System Administrator', 'childsmile_app_tutorships', 'CREATE'),
        ('System Administrator', 'childsmile_app_tutorships', 'UPDATE'),
        ('System Administrator', 'childsmile_app_tutorships', 'DELETE'),
        ('System Administrator', 'childsmile_app_tutorships', 'VIEW'),
        ('System Administrator', 'childsmile_app_matures', 'CREATE'),
        ('System Administrator', 'childsmile_app_matures', 'UPDATE'),
        ('System Administrator', 'childsmile_app_matures', 'DELETE'),
        ('System Administrator', 'childsmile_app_matures', 'VIEW'),
        ('System Administrator', 'childsmile_app_healthy', 'CREATE'),
        ('System Administrator', 'childsmile_app_healthy', 'UPDATE'),
        ('System Administrator', 'childsmile_app_healthy', 'DELETE'),
        ('System Administrator', 'childsmile_app_healthy', 'VIEW'),
        ('System Administrator', 'childsmile_app_feedback', 'CREATE'),
        ('System Administrator', 'childsmile_app_feedback', 'UPDATE'),
        ('System Administrator', 'childsmile_app_feedback', 'DELETE'),
        ('System Administrator', 'childsmile_app_feedback', 'VIEW'),
        ('System Administrator', 'childsmile_app_tasks', 'CREATE'),
        ('System Administrator', 'childsmile_app_tasks', 'UPDATE'),
        ('System Administrator', 'childsmile_app_tasks', 'DELETE'),
        ('System Administrator', 'childsmile_app_tasks', 'VIEW'),
        ('System Administrator', 'childsmile_app_task_types', 'CREATE'),
        ('System Administrator', 'childsmile_app_task_types', 'UPDATE'),
        ('System Administrator', 'childsmile_app_task_types', 'DELETE'),
        ('System Administrator', 'childsmile_app_task_types', 'VIEW'),
        ('System Administrator', 'childsmile_app_tutor_feedback', 'CREATE'),
        ('System Administrator', 'childsmile_app_tutor_feedback', 'UPDATE'),
        ('System Administrator', 'childsmile_app_tutor_feedback', 'DELETE'),
        ('System Administrator', 'childsmile_app_tutor_feedback', 'VIEW'),
        ('System Administrator', 'childsmile_app_general_v_feedback', 'CREATE'),
        ('System Administrator', 'childsmile_app_general_v_feedback', 'UPDATE'),
        ('System Administrator', 'childsmile_app_general_v_feedback', 'DELETE'),
        ('System Administrator', 'childsmile_app_general_v_feedback', 'VIEW'),

        # General Volunteer
        ('General Volunteer', 'childsmile_app_signedup', 'CREATE'),
        ('General Volunteer', 'childsmile_app_signedup', 'UPDATE'),
        ('General Volunteer', 'childsmile_app_signedup', 'DELETE'),
        ('General Volunteer', 'childsmile_app_signedup', 'VIEW'),
        ('General Volunteer', 'childsmile_app_general_volunteer', 'CREATE'),
        ('General Volunteer', 'childsmile_app_general_volunteer', 'UPDATE'),
        ('General Volunteer', 'childsmile_app_general_volunteer', 'DELETE'),
        ('General Volunteer', 'childsmile_app_general_volunteer', 'VIEW'),
        ('General Volunteer', 'childsmile_app_pending_tutor', 'CREATE'),
        ('General Volunteer', 'childsmile_app_pending_tutor', 'UPDATE'),
        ('General Volunteer', 'childsmile_app_pending_tutor', 'DELETE'),
        ('General Volunteer', 'childsmile_app_pending_tutor', 'VIEW'),
        ('General Volunteer', 'childsmile_app_tutors', 'VIEW'),
        ('General Volunteer', 'childsmile_app_feedback', 'CREATE'),
        ('General Volunteer', 'childsmile_app_feedback', 'UPDATE'),
        ('General Volunteer', 'childsmile_app_feedback', 'VIEW'),
        ('General Volunteer', 'childsmile_app_general_v_feedback', 'CREATE'),
        ('General Volunteer', 'childsmile_app_general_v_feedback', 'UPDATE'),
        ('General Volunteer', 'childsmile_app_general_v_feedback', 'VIEW'),
        ('General Volunteer', 'childsmile_app_tasks', 'CREATE'),
        ('General Volunteer', 'childsmile_app_tasks', 'UPDATE'),
        ('General Volunteer', 'childsmile_app_tasks', 'DELETE'),
        ('General Volunteer', 'childsmile_app_tasks', 'VIEW'),
        ('General Volunteer', 'childsmile_app_task_types', 'VIEW'),

        # Tutor
        ('Tutor', 'childsmile_app_signedup', 'CREATE'),
        ('Tutor', 'childsmile_app_signedup', 'UPDATE'),
        ('Tutor', 'childsmile_app_signedup', 'DELETE'),
        ('Tutor', 'childsmile_app_signedup', 'VIEW'),
        ('Tutor', 'childsmile_app_general_volunteer', 'VIEW'),
        ('Tutor', 'childsmile_app_pending_tutor', 'CREATE'),
        ('Tutor', 'childsmile_app_pending_tutor', 'UPDATE'),
        ('Tutor', 'childsmile_app_pending_tutor', 'DELETE'),
        ('Tutor', 'childsmile_app_pending_tutor', 'VIEW'),
        ('Tutor', 'childsmile_app_tutors', 'CREATE'),
        ('Tutor', 'childsmile_app_tutors', 'UPDATE'),
        ('Tutor', 'childsmile_app_tutors', 'DELETE'),
        ('Tutor', 'childsmile_app_tutors', 'VIEW'),
        ('Tutor', 'childsmile_app_children', 'UPDATE'),
        ('Tutor', 'childsmile_app_children', 'VIEW'),
        ('Tutor', 'childsmile_app_tutorships', 'CREATE'),
        ('Tutor', 'childsmile_app_tutorships', 'UPDATE'),
        ('Tutor', 'childsmile_app_tutorships', 'DELETE'),
        ('Tutor', 'childsmile_app_tutorships', 'VIEW'),
        ('Tutor', 'childsmile_app_matures', 'CREATE'),
        ('Tutor', 'childsmile_app_matures', 'UPDATE'),
        ('Tutor', 'childsmile_app_matures', 'DELETE'),
        ('Tutor', 'childsmile_app_matures', 'VIEW'),
        ('Tutor', 'childsmile_app_healthy', 'CREATE'),
        ('Tutor', 'childsmile_app_healthy', 'UPDATE'),
        ('Tutor', 'childsmile_app_healthy', 'DELETE'),
        ('Tutor', 'childsmile_app_healthy', 'VIEW'),
        ('Tutor', 'childsmile_app_feedback', 'CREATE'),
        ('Tutor', 'childsmile_app_feedback', 'UPDATE'),
        ('Tutor', 'childsmile_app_feedback', 'VIEW'),
        ('Tutor', 'childsmile_app_tutor_feedback', 'CREATE'),
        ('Tutor', 'childsmile_app_tutor_feedback', 'UPDATE'),
        ('Tutor', 'childsmile_app_tutor_feedback', 'VIEW'),
        ('Tutor', 'childsmile_app_tasks', 'CREATE'),
        ('Tutor', 'childsmile_app_tasks', 'UPDATE'),
        ('Tutor', 'childsmile_app_tasks', 'DELETE'),
        ('Tutor', 'childsmile_app_tasks', 'VIEW'),
        ('Tutor', 'childsmile_app_task_types', 'VIEW'),

        # Technical Coordinator
        ('Technical Coordinator', 'childsmile_app_staff', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_staff', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_staff', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_staff', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_signedup', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_signedup', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_signedup', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_signedup', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_general_volunteer', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_general_volunteer', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_general_volunteer', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_general_volunteer', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_pending_tutor', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_pending_tutor', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_pending_tutor', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_pending_tutor', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_tutors', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_tutors', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_tutors', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_tutors', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_children', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_children', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_children', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_children', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_tutorships', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_matures', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_healthy', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_feedback', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_tutor_feedback', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_general_v_feedback', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_tasks', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_tasks', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_tasks', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_tasks', 'VIEW'),
        ('Technical Coordinator', 'childsmile_app_task_types', 'CREATE'),
        ('Technical Coordinator', 'childsmile_app_task_types', 'UPDATE'),
        ('Technical Coordinator', 'childsmile_app_task_types', 'DELETE'),
        ('Technical Coordinator', 'childsmile_app_task_types', 'VIEW'),

        # Volunteer Coordinator
        ('Volunteer Coordinator', 'childsmile_app_staff', 'CREATE'),
        ('Volunteer Coordinator', 'childsmile_app_staff', 'UPDATE'),
        ('Volunteer Coordinator', 'childsmile_app_staff', 'DELETE'),
        ('Volunteer Coordinator', 'childsmile_app_staff', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_signedup', 'CREATE'),
        ('Volunteer Coordinator', 'childsmile_app_signedup', 'UPDATE'),
        ('Volunteer Coordinator', 'childsmile_app_signedup', 'DELETE'),
        ('Volunteer Coordinator', 'childsmile_app_signedup', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_general_volunteer', 'CREATE'),
        ('Volunteer Coordinator', 'childsmile_app_general_volunteer', 'UPDATE'),
        ('Volunteer Coordinator', 'childsmile_app_general_volunteer', 'DELETE'),
        ('Volunteer Coordinator', 'childsmile_app_general_volunteer', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_pending_tutor', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_tutors', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_feedback', 'CREATE'),
        ('Volunteer Coordinator', 'childsmile_app_feedback', 'UPDATE'),
        ('Volunteer Coordinator', 'childsmile_app_feedback', 'DELETE'),
        ('Volunteer Coordinator', 'childsmile_app_feedback', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_general_v_feedback', 'CREATE'),
        ('Volunteer Coordinator', 'childsmile_app_general_v_feedback', 'UPDATE'),
        ('Volunteer Coordinator', 'childsmile_app_general_v_feedback', 'DELETE'),
        ('Volunteer Coordinator', 'childsmile_app_general_v_feedback', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_tasks', 'CREATE'),
        ('Volunteer Coordinator', 'childsmile_app_tasks', 'UPDATE'),
        ('Volunteer Coordinator', 'childsmile_app_tasks', 'DELETE'),
        ('Volunteer Coordinator', 'childsmile_app_tasks', 'VIEW'),
        ('Volunteer Coordinator', 'childsmile_app_task_types', 'VIEW'),

        # Families Coordinator
        ('Families Coordinator', 'childsmile_app_signedup', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_general_volunteer', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_pending_tutor', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_tutors', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_children', 'CREATE'),
        ('Families Coordinator', 'childsmile_app_children', 'UPDATE'),
        ('Families Coordinator', 'childsmile_app_children', 'DELETE'),
        ('Families Coordinator', 'childsmile_app_children', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_tutorships', 'CREATE'),
        ('Families Coordinator', 'childsmile_app_tutorships', 'UPDATE'),
        ('Families Coordinator', 'childsmile_app_tutorships', 'DELETE'),
        ('Families Coordinator', 'childsmile_app_tutorships', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_matures', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_healthy', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_tasks', 'CREATE'),
        ('Families Coordinator', 'childsmile_app_tasks', 'UPDATE'),
        ('Families Coordinator', 'childsmile_app_tasks', 'DELETE'),
        ('Families Coordinator', 'childsmile_app_tasks', 'VIEW'),
        ('Families Coordinator', 'childsmile_app_task_types', 'VIEW'),

        # Tutors Coordinator
        ('Tutors Coordinator', 'childsmile_app_staff', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_staff', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_staff', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_staff', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_signedup', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_signedup', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_signedup', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_signedup', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_general_volunteer', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_pending_tutor', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_pending_tutor', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_pending_tutor', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_pending_tutor', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_tutors', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_tutors', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_tutors', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_tutors', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_children', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_children', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_children', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_children', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_tutorships', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_tutorships', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_tutorships', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_tutorships', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_matures', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_healthy', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_feedback', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_feedback', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_feedback', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_feedback', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_tutor_feedback', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_tutor_feedback', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_tutor_feedback', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_tutor_feedback', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_tasks', 'CREATE'),
        ('Tutors Coordinator', 'childsmile_app_tasks', 'UPDATE'),
        ('Tutors Coordinator', 'childsmile_app_tasks', 'DELETE'),
        ('Tutors Coordinator', 'childsmile_app_tasks', 'VIEW'),
        ('Tutors Coordinator', 'childsmile_app_task_types', 'VIEW'),

        # Matures Coordinator
        ('Matures Coordinator', 'childsmile_app_signedup', 'VIEW'),
        ('Matures Coordinator', 'childsmile_app_tutors', 'VIEW'),
        ('Matures Coordinator', 'childsmile_app_children', 'CREATE'),
        ('Matures Coordinator', 'childsmile_app_children', 'UPDATE'),
        ('Matures Coordinator', 'childsmile_app_children', 'DELETE'),
        ('Matures Coordinator', 'childsmile_app_children', 'VIEW'),
        ('Matures Coordinator', 'childsmile_app_tutorships', 'VIEW'),
        ('Matures Coordinator', 'childsmile_app_matures', 'CREATE'),
        ('Matures Coordinator', 'childsmile_app_matures', 'UPDATE'),
        ('Matures Coordinator', 'childsmile_app_matures', 'DELETE'),
        ('Matures Coordinator', 'childsmile_app_matures', 'VIEW'),
        ('Matures Coordinator', 'childsmile_app_tasks', 'CREATE'),
        ('Matures Coordinator', 'childsmile_app_tasks', 'UPDATE'),
        ('Matures Coordinator', 'childsmile_app_tasks', 'DELETE'),
        ('Matures Coordinator', 'childsmile_app_tasks', 'VIEW'),
        ('Matures Coordinator', 'childsmile_app_task_types', 'VIEW'),

        # Healthy Kids Coordinator
        ('Healthy Kids Coordinator', 'childsmile_app_tutors', 'VIEW'),
        ('Healthy Kids Coordinator', 'childsmile_app_children', 'CREATE'),
        ('Healthy Kids Coordinator', 'childsmile_app_children', 'UPDATE'),
        ('Healthy Kids Coordinator', 'childsmile_app_children', 'DELETE'),
        ('Healthy Kids Coordinator', 'childsmile_app_children', 'VIEW'),
        ('Healthy Kids Coordinator', 'childsmile_app_tutorships', 'VIEW'),
        ('Healthy Kids Coordinator', 'childsmile_app_healthy', 'CREATE'),
        ('Healthy Kids Coordinator', 'childsmile_app_healthy', 'UPDATE'),
        ('Healthy Kids Coordinator', 'childsmile_app_healthy', 'DELETE'),
        ('Healthy Kids Coordinator', 'childsmile_app_healthy', 'VIEW'),
        ('Healthy Kids Coordinator', 'childsmile_app_tasks', 'CREATE'),
        ('Healthy Kids Coordinator', 'childsmile_app_tasks', 'UPDATE'),
        ('Healthy Kids Coordinator', 'childsmile_app_tasks', 'DELETE'),
        ('Healthy Kids Coordinator', 'childsmile_app_tasks', 'VIEW'),
        ('Healthy Kids Coordinator', 'childsmile_app_task_types', 'VIEW'),
    ]

    for role_name, resource, action in permissions:
            role = role_objects[role_name]
            Permissions.objects.create(role=role, resource=resource, action=action)

class Migration(migrations.Migration):

    dependencies = [
        ('childsmile_app', '0004_create_initial_roles_and_permissions'),
    ]

    operations = [
        migrations.RunPython(override_roles_and_permissions),
    ]