-- insert  all values from actions.json into AuditTranslation table
INSERT INTO childsmile_app_audittranslation (action, hebrew_translation) VALUES
    ('CREATE_VOLUNTEER_SUCCESS', 'יצירת מתנדב כללי הצליחה'),
    ('DELETE_FAMILY_FAILED', 'כישלון במחיקת משפחה'),
    ('DELETE_FAMILY_SUCCESS', 'מחיקת משפחה הצליחה'),
    ('DELETE_INITIAL_FAMILY_FAILED', 'כישלון במחיקת פרטי משפחה'),
    ('DELETE_INITIAL_FAMILY_SUCCESS', 'מחיקת פרטי משפחה הצליחה'),
    ('DELETE_PENDING_TUTOR_SUCCESS', 'מחיקת מועמד לחונכות הצליחה'),
    ('DELETE_STAFF_FAILED', 'כישלון במחיקת איש צוות'),
    ('DELETE_STAFF_SUCCESS', 'מחיקת איש צוות הצליחה'),
    ('DELETE_TASK_FAILED', 'כישלון במחיקת משימה'),
    ('DELETE_TASK_SUCCESS', 'מחיקת משימה הצליחה'),
    ('DELETE_TUTORSHIP_FAILED', 'כישלון במחיקת חונכות'),
    ('DELETE_TUTORSHIP_SUCCESS', 'מחיקת חונכות הצליחה'),
    ('DELETE_TUTOR_FEEDBACK_FAILED', 'כישלון במחיקת משוב חונך'),
    ('DELETE_TUTOR_FEEDBACK_SUCCESS', 'מחיקת משוב חונך הצליחה'),
    ('DELETE_VOLUNTEER_FEEDBACK_FAILED', 'כישלון במחיקת משוב מתנדב כללי'),
    ('DELETE_VOLUNTEER_FEEDBACK_SUCCESS', 'מחיקת משוב מתנדב כללי הצליחה'),
    ('EXPORT_REPORT_EXCEL_FAILED', 'כישלון ביצוא דוח לאקסל'),
    ('EXPORT_REPORT_EXCEL_SUCCESS', 'יצוא דוח לאקסל הצליח'),
    ('EXPORT_REPORT_IMAGE_FAILED', 'כישלון ביצוא דוח לתמונה'),
    ('EXPORT_REPORT_IMAGE_SUCCESS', 'יצוא דוח לתמונה הצליח'),
    ('UPDATE_FAMILY_FAILED', 'כישלון בעדכון משפחה'),
    ('UPDATE_FAMILY_SUCCESS', 'עדכון משפחה הצליח'),
    ('UPDATE_GENERAL_VOLUNTEER_FAILED', 'כישלון בעדכון מתנדב כללי'),
    ('UPDATE_GENERAL_VOLUNTEER_SUCCESS', 'עדכון מתנדב כללי הצליח'),
    ('UPDATE_STAFF_FAILED', 'כישלון בעדכון איש צוות'),
    ('UPDATE_STAFF_SUCCESS', 'עדכון איש צוות הצליח'),
    ('UPDATE_TASK_FAILED', 'כישלון בעדכון משימה'),
    ('UPDATE_TASK_SUCCESS', 'עדכון משימה הצליח'),
    ('UPDATE_TUTORSHIP_FAILED', 'כישלון בעדכון חונכות'),
    ('UPDATE_TUTORSHIP_SUCCESS', 'עדכון חונכות הצליח'),
    ('UPDATE_TUTOR_FAILED', 'כישלון בעדכון חונך'),
    ('UPDATE_TUTOR_FEEDBACK_FAILED', 'כישלון בעדכון משוב חונך'),
    ('UPDATE_TUTOR_FEEDBACK_SUCCESS', 'עדכון משוב חונך הצליח'),
    ('UPDATE_TUTOR_SUCCESS', 'עדכון חונך הצליח'),
    ('UPDATE_VOLUNTEER_FEEDBACK_FAILED', 'כישלון בעדכון משוב מתנדב כללי'),
    ('UPDATE_VOLUNTEER_FEEDBACK_SUCCESS', 'עדכון משוב מתנדב כללי הצליח'),
    ('USER_LOGIN_FAILED', 'כישלון בהתחברות משתמש'),
    ('USER_LOGIN_SUCCESS', 'התחברות משתמש הצליחה'),
    ('USER_LOGOUT', 'התנתקות משתמש'),
    ('VIEW_FAMILY_DETAILS_FAILED', 'כישלון בצפייה בפרטי משפחה'),
    ('VIEW_INITIAL_FAMILY_FAILED', 'כישלון בצפייה במשפחה ראשונית'),
    ('VIEW_TASKS_SUCCESS', 'צפייה במשימות הצליחה'),
    ('VIEW_TUTOR_FEEDBACK_FAILED', 'כישלון בצפייה במשוב חונך'),
    ('VIEW_VOLUNTEER_FEEDBACK_FAILED', 'כישלון בצפייה במשוב מתנדב כללי'),
    ('VIEW_VOLUNTEER_FEEDBACK_SUCCESS', 'צפייה במשוב מתנדב כללי הצליחה');   
    ('CREATE_FAMILY_FAILED', 'כישלון ביצירת משפחה'),
    ('CREATE_FAMILY_SUCCESS', 'יצירת משפחה הצליחה'),
    ('CREATE_PENDING_TUTOR_SUCCESS', 'יצירת מועמד לחונכות הצליחה'),
    ('CREATE_STAFF_FAILED', 'כישלון ביצירת איש צוות'),
    ('CREATE_STAFF_SUCCESS', 'יצירת איש צוות הצליחה'),
    ('CREATE_TASK_FAILED', 'כישלון ביצירת משימה'),
    ('CREATE_TASK_SUCCESS', 'יצירת משימה הצליחה'),
    ('CREATE_TUTORSHIP_FAILED', 'כישלון ביצירת חונכות'),
    ('CREATE_TUTORSHIP_SUCCESS', 'יצירת חונכות הצליחה'),
    ('CREATE_TUTOR_FEEDBACK_FAILED', 'כישלון ביצירת משוב חונך'),
    ('CREATE_TUTOR_FEEDBACK_SUCCESS', 'יצירת משוב חונך הצליחה'),
    ('CREATE_VOLUNTEER_FAILED', 'כישלון ביצירת מתנדב'),
    ('CREATE_VOLUNTEER_FEEDBACK_FAILED', 'כישלון ביצירת משוב מתנדב כללי'),
    ('CREATE_VOLUNTEER_FEEDBACK_SUCCESS', 'יצירת משוב מתנדב כללי הצליחה'),
    ('EXPORT_REPORT_PDF_FAILED', 'כישלון ביצוא דוח ל-PDF'),
    ('EXPORT_REPORT_PDF_SUCCESS', 'יצוא דוח ל-PDF הצליח'),
    ('GOOGLE_LOGIN_FAILED', 'כישלון בהתחברות עם גוגל'),
    ('GOOGLE_LOGIN_SUCCESS', 'התחברות עם גוגל הצליחה'),
    ('MARK_FAMILY_ADDED_FAILED', 'כישלון בסימון משפחה כהתווספה'),
    ('MARK_FAMILY_ADDED_SUCCESS', 'סימון משפחה כהתווספה הצליח'),
    ('TOTP_VERIFICATION_FAILED', 'כישלון באימות TOTP'),
    ('TOTP_VERIFICATION_SUCCESS', 'אימות TOTP הצליח'),
    ('USER_REGISTRATION_FAILED', 'כישלון בהרשמת משתמש'),
    ('USER_REGISTRATION_SUCCESS', 'הרשמת משתמש הצליחה');
-- end of additional insert statements